export { default as HeroTexts } from "./HeroTexts/HeroTexts"
export { default as HeroImage } from "./HeroImage/HeroImage"
export { default as AboutDev } from "./AboutDev/AboutDev"
export { default as About3D } from "./About3D/About3D"
export { default as CardWorks } from "./CardWorks/CardWorks"
export { default as FormContact } from "./FormContact/FormContact"
