export { default as Navbar } from "./Navbar/Navbar"
export { default as HomeSection } from "./HomeSection/HomeSection"
export { default as AboutSection } from "./AboutSection/AboutSection"
export { default as WorkSection } from "./WorkSection/WorkSection"
export { default as ContactSection } from "./ContactSection/ContactSection"